# Generated by Django 4.1 on 2022-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(max_length=255)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('video_quality', models.CharField(choices=[('good', 'good'), ('better', 'better'), ('best', 'best')], max_length=6)),
                ('video_resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K+HDR', '4K+HDR')], max_length=6)),
            ],
        ),
    ]
