# Generated by Django 4.1 on 2022-11-11 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('flyer', models.ImageField(upload_to='media/images/')),
                ('release_date', models.DateField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('seasonal', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='movies', to='movies.category')),
            ],
        ),
    ]
