# Generated by Django 4.1 on 2022-11-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
